var OPTIONS = {
	like_what: 'subscribed',
	like_timer: 'instant',
	minute_timer: false,
	minute_value: 10,
	percentage_timer: true,
	percentage_value: 5,
	use_list: false,
	type_list: 'black',
	plugin_version: "0.0.0",
	creator_list: [],
	debug: false,
	debug_displayed: false,
	counter: 0,
}